version: 1.13.0.{build}
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true
environment:
  lslversion: 1.13.0-b3
  OCTAVE_VER: 4.4.1-w64
  LSLDIST_URL: "https://github.com/sccn/liblsl/releases/download"
  CMakeArgs: ""
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
install:
- cmd: appveyor DownloadFile %LSLDIST_URL%/%lslversion%/liblsl-%lslversion%-Win64.7z -FileName liblsl_x64.7z
- cmd: appveyor DownloadFile https://ftp.gnu.org/gnu/octave/windows/octave-%OCTAVE_VER%.7z -FileName octave.7z 
- cmd: 7z x octave.7z -oC:\projects\deps > nul
- cmd: 7z x liblsl_x64.7z
- cmd: set PATH=C:\projects\deps\octave-%OCTAVE_VER%\bin;%PATH%
build_script:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
- cmd: cp LSL/lib/liblsl64.dll bin/
- octave-cli --eval build_mex
- cmd: del bin\*.o
artifacts:
- path: .
  name: ${APPVEYOR_PROJECT_NAME}_x64_${APPVEYOR_BUILD_VERSION}
