language: c
dist: xenial
env:
  LSLDIST_URL="https://github.com/sccn/liblsl/releases/download/"
  UBUNTU_DIST="Linux64-xenial"
  LSL_VERSION="1.13.0-b3"
  - CMakeArgs=""
matrix:
  include:
  - os: linux
    addons:
      apt:
        packages:
        - liboctave-dev
    before_script:
    - travis_retry wget --quiet ${LSLDIST_URL}/liblsl/liblsl-${LSL_VERSION}-${UBUNTU_DIST}.deb
    - dpkg -x *.deb LSL
    - export LSL_INSTALL_ROOT=LSL/usr
  - os: osx
    before_install:
    - brew install octave
    before_script:
      - travis_retry wget ${LSLDIST_URL}/${LSL_VERSION}/liblsl-${LSL_VERSION}-OSX64.tar.bz2
      - mkdir LSL; tar -xf *.tar.bz2 -C LSL
      - export LSL_INSTALL_ROOT=LSL
script:
- cp ${LSL_INSTALL_ROOT}/lib/* bin/
- octave-cli --eval build_mex
- rm bin/*.o
- tar --transform "s/^\.\?/liblsl-matlab/" -cjf liblsl-matlab-${LSL_VERSION}.tar.bz2 . || true
